Move lightouse CI to dev CI

diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -38,6 +38,24 @@ jobs:
           build: yarn run build
           start: yarn run dev
 
+  lhci:
+    name: Lighthouse CI
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v1
+      - name: Use Node.js 16.17.1
+        uses: actions/setup-node@v1
+        with:
+          node-version: 16.17.1
+      - name: Install
+        run: |
+          npm install -g yarn
+      - run : yarn install --frozen-lockfile
+      - name: run Lighthouse CI
+        run: |
+          yarn install -g @lhci/cli@0.3.x
+          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
+
   deploy-app:
     if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
     environment: dev
